Fix backend import
The import was incorrect for the package created with `yarn new`.

The correct name is what matches `package.json` in the generated plugin
directory:

```
jq -r .name plugins/auth-backend-module-holos-proxy-provider/package.json
@internal/backstage-plugin-auth-backend-module-holos-proxy-provider
```

Additionally, the following works, but may not be necessary:

```
yarn --cwd packages/backend add "@internal/backstage-plugin-auth-backend-module-holos-proxy-provider@^0.1.0"
```

Without this patch the container builds but fails to run with:

```
❯ k logs -f backstage-56c88587f7-dldz5
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@internal/plugin-auth-backend-module-holos-proxy-provider' imported from /app/packages/backend/dist/index.cjs.js
    at new NodeError (node:internal/errors:405:5)
    at packageResolve (node:internal/modules/esm/resolve:916:9)
    at moduleResolve (node:internal/modules/esm/resolve:973:20)
    at defaultResolve (node:internal/modules/esm/resolve:1193:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:404:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:373:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:250:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:336:34)
    at importModuleDynamically (node:internal/modules/cjs/loader:1256:33)
    at importModuleDynamicallyWrapper (node:internal/vm/module:432:21) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v18.20.3
```

With this patch applied, we get further but we haven't added the
resolver to the auth plugin and I'm not sure how we can.

```
{"level":"info","message":"Configuring auth provider: holosProxy","plugin":"auth","service":"backstage"}
/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1859
          throw new errors.ForwardedError(
                ^

ForwardedError: Plugin 'auth' startup failed; caused by Error: Failed to initialize holosProxy auth provider, No sign-in resolver configured for proxy auth provider 'holosProxy'
    at /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1859:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1858:9
    ... 3 lines matching cause stack trace ...
    at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1949:5) {
  cause: Error: Failed to initialize holosProxy auth provider, No sign-in resolver configured for proxy auth provider 'holosProxy'
      at bindProviderRouters (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:1722:17)
      at createRouter (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:2468:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.init [as func] (/app/node_modules/@backstage/plugin-auth-backend/dist/index.cjs.js:2535:24)
      at async /app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1858:9
      at async Promise.all (index 4)
      at async BackendInitializer.doStart_fn (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1819:3)
      at async BackendInitializer.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1675:5)
      at async BackstageBackend.start (/app/node_modules/@backstage/backend-app-api/dist/index.cjs.js:1949:5)
}

Node.js v18.20.3
```